---
title: "Bitacora - TraumaTron"
output: 
  html_notebook: 
    theme: readable
    toc: yes
author: Avilés, Gener; González, Ricardo.
bibliography: references.bib
---

##Planteamiento del problema
El proceso de interpretación de imágenes médicas, en concreto las proyecciones obtenidas por rayos x en el contexto de patologías traumatológicas, es una actividad que depende principalmente de la apreciación del clínico.
El volumen de pacientes atendidos en la consulta promedio de traumatología reduce el tiempo que el clínico puede dedicarle al análisis detallado de las placas.
Ésta realidad motivó la exploración de las posibilidades de automatización del proceso de análisis de placas óseas por rayos x, en particular las proyecciones laterales de columna cervical.
El uso de aproximaciones de aprendizaje automatizado e inteligencia artificial para el análisis de rayos x es un tema de actual interés, como lo podemos ver en los trabajos de @lakhani2017 y @Le2011.
En éste proyecto nos aproximamos al problema con las estrategias de:

- **Procesamiento Digital de Imágenes** para la identificación de estructuras óseas y medición de ángulos y relaciones,
- **Reducción de Dimensionalidad** para transformar los datos de imágenes en protocolo DICOM (*Digital Imaging and Communications in Medicine*) a un conjunto de datos con menos dimensiones.
- **Algoritmos de Aprendizaje Automatizado** para la clasificación (diagnóstico) de los datos, una vez procesados, con el objetivo de que el resultado final sea accesible a los clínicos.


##Teoría
###Ecualización por Histograma

Para una imagen dada $X$ la función de densidad de probabilidad $p(X_k)$ está definida como:
$$\begin{equation}
p(X_k) =\frac{n^k}{n}
\end{equation}$$
Para $k=0,...,L-1$ donde, $L$ es el valor mas alto en intervalo dinámico, $n^k$ representa el número de veces que el nivel de $X_k$ aparece en la imagen de entrada $X$ y $n$ es el total de muestras en la imagen de entrada. 
Notar que si se grafica $n^k$ vs. $X_k$ obtenemos el histograma de la imagen.

La función de densidad acumulada está dada por:
$$\begin{equation}
c(X) =\sum_{j=0}^{k} p(X_j)
\end{equation}$$

Notar que $c(X_{L-1}) = 1$ en el rango dinámico $(X_0,X_{L-1})$. Se define una función de transformación $f(x)$, basada en la función de densidad acumulada como:


##Prubeas de concepto
###Scripts de ejemplo y resultados

##Referencias